### **In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow**

##### *More specifically, we're going to cover:*
#####* Introduction to Tensors
#####* Getting information from Tensors
#####* Manipulating Tensors
#####* Tensors & NumPy
#####* Using @tf.function (a way to speed up your regular Python functions)
#####* Using GPUs with TensorFlow (or TPUs)
#####* Exercises to try for yourself 

### Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant ([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant ([[10, 7],
                       [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check the dimension of our matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # Specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number dimensions of another_matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant ([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# What's the number dimensions of tensor?
tensor.ndim

3

###**What we've created so far:**

##### * Scalar: a single number
##### * Vector: a number with direction (e.g. wind speed and direction)
##### * Matrix: a 2-dimensional array of numbers
##### * Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create the same tensor with tf.Vairable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

##### **Note**: Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as Tensorflow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

##### Random tensors are tensors of some arbitary size which contain random numbers.

In [ ]:
# Create two random (but the sam) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducability
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**EXERCISE**

##### ✍︎ **Exercise**: Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

In [ ]:
# Shuffling the first tensor
tens1 = tf.constant([[10,7],
                    [40, 19],
                    [19, 100]]) 
tens1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 40,  19],
       [ 19, 100]], dtype=int32)>

In [ ]:
tens1.ndim

2

In [ ]:
tf.random.shuffle(tens1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 40,  19],
       [ 19, 100]], dtype=int32)>

In [ ]:
tf.random.set_seed(50)
tf.random.shuffle(tens1, seed=50)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 19, 100],
       [ 40,  19],
       [ 10,   7]], dtype=int32)>

In [ ]:
# Experimenting with seeds
tf.random.set_seed(50)
tf.random.shuffle(tens1, seed=19)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 40,  19],
       [ 19, 100]], dtype=int32)>

In [ ]:
# Shuffling the second tensor
tens2 = tf.constant([[99, 199, 50],
                     [99, 83, 695],
                     [75, 89, 22],
                     [65, 9999, 20]])
tens2

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  99,  199,   50],
       [  99,   83,  695],
       [  75,   89,   22],
       [  65, 9999,   20]], dtype=int32)>

In [ ]:
tens2.ndim

2

In [ ]:
tf.random.shuffle(tens2)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  65, 9999,   20],
       [  99,  199,   50],
       [  75,   89,   22],
       [  99,   83,  695]], dtype=int32)>

In [ ]:
tf.random.set_seed(99)
tf.random.shuffle(tens2, seed=99)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  99,  199,   50],
       [  75,   89,   22],
       [  99,   83,  695],
       [  65, 9999,   20]], dtype=int32)>

In [ ]:
tf.random.shuffle(tens2, seed=1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  65, 9999,   20],
       [  75,   89,   22],
       [  99,  199,   50],
       [  99,   83,  695]], dtype=int32)>

In [ ]:
# Shuffling the third tensor
tens3 = ([[55, 67, 86, 99],
          [86, 96, 90],
          [85, 37, 84, 239, 49],
          [84, 93],
          [65, 90, 82]])
tens3

[[55, 67, 86, 99], [86, 96, 90], [85, 37, 84, 239, 49], [84, 93], [65, 90, 82]]

In [ ]:
tens3.ndim

AttributeError: ignored

In [ ]:
# Shuffling the fourth tensor
tens4 = tf.constant([[89, 80],
                     [90, 99],
                     [969, 6565],
                     [84, 754]])
tens4

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[  89,   80],
       [  90,   99],
       [ 969, 6565],
       [  84,  754]], dtype=int32)>

In [ ]:
tens4.ndim

2

In [ ]:
tf.random.shuffle(tens4)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[  90,   99],
       [  84,  754],
       [  89,   80],
       [ 969, 6565]], dtype=int32)>

In [ ]:
tf.random.set_seed(1092)
tf.random.shuffle(tens4, seed=1092)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[  84,  754],
       [  90,   99],
       [  89,   80],
       [ 969, 6565]], dtype=int32)>

In [ ]:
# Experimentation with seed=
tf.random.set_seed(1092)
tf.random.shuffle(tens4, seed=1000)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 969, 6565],
       [  90,   99],
       [  84,  754],
       [  89,   80]], dtype=int32)>

In [ ]:
# Shuffling the fifth tensor
tens5 = tf.constant([[98, 100, 1000, 10000],
                     [89, 90, 98, 987],
                     [89, 74, 822, 736]])
tens5

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[   98,   100,  1000, 10000],
       [   89,    90,    98,   987],
       [   89,    74,   822,   736]], dtype=int32)>

In [ ]:
tens5.ndim

2

In [ ]:
tf.random.shuffle(tens5)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[   89,    90,    98,   987],
       [   98,   100,  1000, 10000],
       [   89,    74,   822,   736]], dtype=int32)>

In [ ]:
tf.random.set_seed(9090)
tf.random.shuffle(tens5, seed=93)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[   98,   100,  1000, 10000],
       [   89,    90,    98,   987],
       [   89,    74,   822,   736]], dtype=int32)>